theme = "docuapi"
# themesdir = "../.."
languageCode = "en-us"
baseurl = "/"
title = "Cloudify API Documentation"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
googleAnalytics = "GTM-P8VJ87"

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "cURL" 
[[params.language_tabs]]
key = "python"
name = "Python"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Cloudify API Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"[Cloudify Documentation Center](https://docs.cloudify.co)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


# [languages.nn]
# languageName = "Nynorsk"
# weight = 1
# title = "DocuAPI-døme"

# # Left sidebar footer items. Use HTMl or Markdown.
# toc_footers = [ 
# "<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
# "Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
# "Hugo Theme av [bep](https://github.com/bep)"
# ]

# [languages.nn.blackfriday]
# # Norwegian uses angled quotes
# angledQuotes = true
# hrefTargetBlank = true

[[menu.shortcuts]]
name = "<i class='fa fa-question-circle'></i> <label>Product</label>"
url = "https://cloudify.co/product"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-address-card'></i> <label>About Us</label>"
url = "https://cloudify.co/about"
weight = 40

[[menu.shortcuts]]
name = "<i class='fa fa-phone-square'></i> <label>Support</label>"
url = "https://cloudify.co/support"
weight = 60

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "https://cloudify.co/download"
weight = 70

[[menu.shortcuts]]
name = "<i class='fa fa-paper-plane'></i> <label>Feedback</label>"
url = "mailto:docs@cloudify.co?subject=Cloudify Documentation Feedback"
weight = 80